"""Initial schema with core healthcare entities

Revision ID: 2e5c82fd60c7
Revises: 
Create Date: 2026-09-19 13:31:56.537881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e5c82fd60c7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chaos_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mode', sa.String(length=50), nullable=True),
    sa.Column('simulated_delay_ms', sa.Integer(), nullable=True),
    sa.Column('failure_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hospitals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=False),
    sa.Column('license_number', sa.String(length=100), nullable=False),
    sa.Column('contact_email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('rejection_reason', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('hospitals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hospitals_license_number'), ['license_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_hospitals_status'), ['status'], unique=False)

    op.create_table('mock_ehr_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('ehr_appointment_id', sa.String(length=100), nullable=False),
    sa.Column('idempotency_key', sa.String(length=100), nullable=False),
    sa.Column('patient_name', sa.String(length=255), nullable=False),
    sa.Column('doctor_name', sa.String(length=255), nullable=False),
    sa.Column('hospital_name', sa.String(length=255), nullable=False),
    sa.Column('slot_time', sa.String(length=100), nullable=False),
    sa.Column('chief_complaint', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ehr_appointment_id')
    )
    with op.batch_alter_table('mock_ehr_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mock_ehr_records_idempotency_key'), ['idempotency_key'], unique=True)

    op.create_table('specialties',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    with op.batch_alter_table('specialties', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_specialties_name'), ['name'], unique=True)

    op.create_table('audit_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('correlation_id', sa.String(length=100), nullable=True),
    sa.Column('hospital_id', sa.String(length=36), nullable=True),
    sa.Column('actor_id', sa.String(length=100), nullable=True),
    sa.Column('actor_role', sa.String(length=50), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=False),
    sa.Column('resource_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.create_index('idx_audit_correlation_tenant', ['correlation_id', 'hospital_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_correlation_id'), ['correlation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_hospital_id'), ['hospital_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_resource_type'), ['resource_type'], unique=False)

    op.create_table('departments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('hospital_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hospital_id', 'name', name='uq_hospital_department_name')
    )
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_departments_hospital_id'), ['hospital_id'], unique=False)

    op.create_table('external_identifier_mappings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('hospital_id', sa.String(length=36), nullable=False),
    sa.Column('system_name', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('internal_id', sa.String(length=100), nullable=False),
    sa.Column('external_id', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('system_name', 'entity_type', 'internal_id', name='uq_sys_entity_internal')
    )
    with op.batch_alter_table('external_identifier_mappings', schema=None) as batch_op:
        batch_op.create_index('idx_ext_mapping_lookup', ['system_name', 'entity_type', 'external_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_external_identifier_mappings_external_id'), ['external_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_external_identifier_mappings_hospital_id'), ['hospital_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_external_identifier_mappings_internal_id'), ['internal_id'], unique=False)

    op.create_table('questionnaires',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('hospital_id', sa.String(length=36), nullable=False),
    sa.Column('specialty_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('questions', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['specialty_id'], ['specialties.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('questionnaires', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_questionnaires_hospital_id'), ['hospital_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_questionnaires_specialty_id'), ['specialty_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('hospital_id', sa.String(length=36), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_hospital_id'), ['hospital_id'], unique=False)

    op.create_table('doctors',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('hospital_id', sa.String(length=36), nullable=False),
    sa.Column('department_id', sa.String(length=36), nullable=True),
    sa.Column('specialty_id', sa.String(length=36), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('specialty', sa.String(length=100), nullable=False),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('qualifications', sa.String(length=255), nullable=True),
    sa.Column('experience_years', sa.Integer(), nullable=True),
    sa.Column('languages', sa.String(length=255), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('consultation_fee', sa.Float(), nullable=True),
    sa.Column('slot_duration_min', sa.Integer(), nullable=True),
    sa.Column('external_provider_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['specialty_id'], ['specialties.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.create_index('idx_doctors_hospital_specialty', ['hospital_id', 'specialty'], unique=False)
        batch_op.create_index(batch_op.f('ix_doctors_department_id'), ['department_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_doctors_external_provider_id'), ['external_provider_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_doctors_hospital_id'), ['hospital_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_doctors_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_doctors_specialty'), ['specialty'], unique=False)
        batch_op.create_index(batch_op.f('ix_doctors_specialty_id'), ['specialty_id'], unique=False)

    op.create_table('hospital_admins',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('hospital_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('role_title', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('hospital_admins', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hospital_admins_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_hospital_admins_hospital_id'), ['hospital_id'], unique=False)

    op.create_table('patients',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('primary_hospital_id', sa.String(length=36), nullable=True),
    sa.Column('patient_mrn', sa.String(length=100), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('date_of_birth', sa.String(length=50), nullable=True),
    sa.Column('gender', sa.String(length=50), nullable=True),
    sa.Column('emergency_contact', sa.String(length=255), nullable=True),
    sa.Column('communication_preference', sa.String(length=50), nullable=True),
    sa.Column('preferences', sa.JSON(), nullable=True),
    sa.Column('external_patient_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['primary_hospital_id'], ['hospitals.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_patients_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_patients_external_patient_id'), ['external_patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_patients_patient_mrn'), ['patient_mrn'], unique=False)
        batch_op.create_index(batch_op.f('ix_patients_phone'), ['phone'], unique=False)
        batch_op.create_index(batch_op.f('ix_patients_primary_hospital_id'), ['primary_hospital_id'], unique=False)

    op.create_table('ai_conversations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=100), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=True),
    sa.Column('hospital_id', sa.String(length=36), nullable=True),
    sa.Column('channel', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('transcript', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_conversations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_conversations_hospital_id'), ['hospital_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_conversations_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_conversations_session_id'), ['session_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_ai_conversations_status'), ['status'], unique=False)

    op.create_table('availability_schedules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('doctor_id', sa.String(length=36), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.String(length=10), nullable=False),
    sa.Column('end_time', sa.String(length=10), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('calendars',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('hospital_id', sa.String(length=36), nullable=False),
    sa.Column('doctor_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('calendars', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_calendars_doctor_id'), ['doctor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_calendars_hospital_id'), ['hospital_id'], unique=False)

    op.create_table('time_slots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('doctor_id', sa.String(length=36), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('hold_expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('time_slots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_time_slots_doctor_id'), ['doctor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_time_slots_start_time'), ['start_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_time_slots_status'), ['status'], unique=False)

    op.create_table('ai_contexts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('hospital_id', sa.String(length=36), nullable=True),
    sa.Column('current_intent', sa.String(length=100), nullable=True),
    sa.Column('selected_hospital_id', sa.String(length=36), nullable=True),
    sa.Column('selected_doctor_id', sa.String(length=36), nullable=True),
    sa.Column('selected_slot_id', sa.String(length=36), nullable=True),
    sa.Column('current_appointment_id', sa.String(length=36), nullable=True),
    sa.Column('extracted_symptoms', sa.JSON(), nullable=True),
    sa.Column('urgency_level', sa.String(length=50), nullable=True),
    sa.Column('preferences', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['ai_conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conversation_id')
    )
    op.create_table('appointments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('appointment_number', sa.String(length=50), nullable=True),
    sa.Column('hospital_id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('doctor_id', sa.String(length=36), nullable=False),
    sa.Column('calendar_id', sa.String(length=36), nullable=True),
    sa.Column('slot_id', sa.String(length=36), nullable=True),
    sa.Column('appointment_type', sa.String(length=50), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('ehr_appointment_id', sa.String(length=100), nullable=True),
    sa.Column('idempotency_key', sa.String(length=100), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('chief_complaint', sa.Text(), nullable=True),
    sa.Column('urgency_level', sa.String(length=50), nullable=True),
    sa.Column('ai_triage_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['calendar_id'], ['calendars.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['slot_id'], ['time_slots.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.create_index('idx_appointments_doctor_date', ['doctor_id', 'start_time'], unique=False)
        batch_op.create_index('idx_appointments_hospital_status', ['hospital_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_appointments_appointment_number'), ['appointment_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_appointments_doctor_id'), ['doctor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_appointments_ehr_appointment_id'), ['ehr_appointment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_appointments_hospital_id'), ['hospital_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_appointments_idempotency_key'), ['idempotency_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_appointments_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_appointments_start_time'), ['start_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_appointments_status'), ['status'], unique=False)

    op.create_table('availabilities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('hospital_id', sa.String(length=36), nullable=False),
    sa.Column('doctor_id', sa.String(length=36), nullable=False),
    sa.Column('calendar_id', sa.String(length=36), nullable=True),
    sa.Column('day_of_week', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.String(length=10), nullable=False),
    sa.Column('end_time', sa.String(length=10), nullable=False),
    sa.Column('slot_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('specific_date', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['calendar_id'], ['calendars.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('availabilities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_availabilities_calendar_id'), ['calendar_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_availabilities_doctor_id'), ['doctor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_availabilities_hospital_id'), ['hospital_id'], unique=False)

    op.create_table('blocked_slots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('hospital_id', sa.String(length=36), nullable=False),
    sa.Column('doctor_id', sa.String(length=36), nullable=False),
    sa.Column('calendar_id', sa.String(length=36), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['calendar_id'], ['calendars.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('blocked_slots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_blocked_slots_calendar_id'), ['calendar_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_blocked_slots_doctor_id'), ['doctor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_blocked_slots_hospital_id'), ['hospital_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_blocked_slots_start_time'), ['start_time'], unique=False)

    op.create_table('ehr_sync_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('appointment_id', sa.String(length=36), nullable=False),
    sa.Column('idempotency_key', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('request_payload', sa.Text(), nullable=True),
    sa.Column('response_payload', sa.Text(), nullable=True),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('integration_operations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('hospital_id', sa.String(length=36), nullable=False),
    sa.Column('appointment_id', sa.String(length=36), nullable=True),
    sa.Column('system_name', sa.String(length=100), nullable=True),
    sa.Column('operation_type', sa.String(length=50), nullable=False),
    sa.Column('idempotency_key', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('request_payload', sa.Text(), nullable=True),
    sa.Column('response_payload', sa.Text(), nullable=True),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('correlation_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('integration_operations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_integration_operations_appointment_id'), ['appointment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_integration_operations_correlation_id'), ['correlation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_integration_operations_hospital_id'), ['hospital_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_integration_operations_idempotency_key'), ['idempotency_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_integration_operations_status'), ['status'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('hospital_id', sa.String(length=36), nullable=True),
    sa.Column('appointment_id', sa.String(length=36), nullable=True),
    sa.Column('recipient_type', sa.String(length=50), nullable=False),
    sa.Column('recipient_contact', sa.String(length=255), nullable=False),
    sa.Column('channel', sa.String(length=50), nullable=True),
    sa.Column('template', sa.String(length=100), nullable=False),
    sa.Column('message_content', sa.Text(), nullable=True),
    sa.Column('scheduled_for', sa.DateTime(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_appointment_id'), ['appointment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_hospital_id'), ['hospital_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_scheduled_for'), ['scheduled_for'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_status'), ['status'], unique=False)

    op.create_table('pre_visit_questionnaires',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('appointment_id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('questions', sa.JSON(), nullable=False),
    sa.Column('answers', sa.JSON(), nullable=True),
    sa.Column('ai_clinical_summary', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('questionnaire_responses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('questionnaire_id', sa.String(length=36), nullable=True),
    sa.Column('appointment_id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('hospital_id', sa.String(length=36), nullable=False),
    sa.Column('answers', sa.JSON(), nullable=True),
    sa.Column('ai_clinical_summary', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['questionnaire_id'], ['questionnaires.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('questionnaire_responses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_questionnaire_responses_appointment_id'), ['appointment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_questionnaire_responses_hospital_id'), ['hospital_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_questionnaire_responses_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_questionnaire_responses_questionnaire_id'), ['questionnaire_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_questionnaire_responses_status'), ['status'], unique=False)

    op.create_table('reconciliation_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('hospital_id', sa.String(length=36), nullable=False),
    sa.Column('appointment_id', sa.String(length=36), nullable=True),
    sa.Column('idempotency_key', sa.String(length=100), nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reconciliation_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reconciliation_records_appointment_id'), ['appointment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reconciliation_records_hospital_id'), ['hospital_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reconciliation_records_idempotency_key'), ['idempotency_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_reconciliation_records_status'), ['status'], unique=False)

    op.create_table('reminder_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('appointment_id', sa.String(length=36), nullable=False),
    sa.Column('reminder_type', sa.String(length=50), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('channel', sa.String(length=50), nullable=True),
    sa.Column('message_content', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('verifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('hospital_id', sa.String(length=36), nullable=False),
    sa.Column('appointment_id', sa.String(length=36), nullable=False),
    sa.Column('idempotency_key', sa.String(length=100), nullable=False),
    sa.Column('external_appointment_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('verifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_verifications_appointment_id'), ['appointment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_verifications_external_appointment_id'), ['external_appointment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_verifications_hospital_id'), ['hospital_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_verifications_idempotency_key'), ['idempotency_key'], unique=False)

    op.create_table('workflows',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('hospital_id', sa.String(length=36), nullable=False),
    sa.Column('appointment_id', sa.String(length=36), nullable=True),
    sa.Column('workflow_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('current_step', sa.Integer(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('execution_history', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workflows', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workflows_appointment_id'), ['appointment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflows_hospital_id'), ['hospital_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflows_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflows', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workflows_status'))
        batch_op.drop_index(batch_op.f('ix_workflows_hospital_id'))
        batch_op.drop_index(batch_op.f('ix_workflows_appointment_id'))

    op.drop_table('workflows')
    with op.batch_alter_table('verifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_verifications_idempotency_key'))
        batch_op.drop_index(batch_op.f('ix_verifications_hospital_id'))
        batch_op.drop_index(batch_op.f('ix_verifications_external_appointment_id'))
        batch_op.drop_index(batch_op.f('ix_verifications_appointment_id'))

    op.drop_table('verifications')
    op.drop_table('reminder_logs')
    with op.batch_alter_table('reconciliation_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reconciliation_records_status'))
        batch_op.drop_index(batch_op.f('ix_reconciliation_records_idempotency_key'))
        batch_op.drop_index(batch_op.f('ix_reconciliation_records_hospital_id'))
        batch_op.drop_index(batch_op.f('ix_reconciliation_records_appointment_id'))

    op.drop_table('reconciliation_records')
    with op.batch_alter_table('questionnaire_responses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_questionnaire_responses_status'))
        batch_op.drop_index(batch_op.f('ix_questionnaire_responses_questionnaire_id'))
        batch_op.drop_index(batch_op.f('ix_questionnaire_responses_patient_id'))
        batch_op.drop_index(batch_op.f('ix_questionnaire_responses_hospital_id'))
        batch_op.drop_index(batch_op.f('ix_questionnaire_responses_appointment_id'))

    op.drop_table('questionnaire_responses')
    op.drop_table('pre_visit_questionnaires')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_status'))
        batch_op.drop_index(batch_op.f('ix_notifications_scheduled_for'))
        batch_op.drop_index(batch_op.f('ix_notifications_hospital_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_appointment_id'))

    op.drop_table('notifications')
    with op.batch_alter_table('integration_operations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_integration_operations_status'))
        batch_op.drop_index(batch_op.f('ix_integration_operations_idempotency_key'))
        batch_op.drop_index(batch_op.f('ix_integration_operations_hospital_id'))
        batch_op.drop_index(batch_op.f('ix_integration_operations_correlation_id'))
        batch_op.drop_index(batch_op.f('ix_integration_operations_appointment_id'))

    op.drop_table('integration_operations')
    op.drop_table('ehr_sync_logs')
    with op.batch_alter_table('blocked_slots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blocked_slots_start_time'))
        batch_op.drop_index(batch_op.f('ix_blocked_slots_hospital_id'))
        batch_op.drop_index(batch_op.f('ix_blocked_slots_doctor_id'))
        batch_op.drop_index(batch_op.f('ix_blocked_slots_calendar_id'))

    op.drop_table('blocked_slots')
    with op.batch_alter_table('availabilities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_availabilities_hospital_id'))
        batch_op.drop_index(batch_op.f('ix_availabilities_doctor_id'))
        batch_op.drop_index(batch_op.f('ix_availabilities_calendar_id'))

    op.drop_table('availabilities')
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_appointments_status'))
        batch_op.drop_index(batch_op.f('ix_appointments_start_time'))
        batch_op.drop_index(batch_op.f('ix_appointments_patient_id'))
        batch_op.drop_index(batch_op.f('ix_appointments_idempotency_key'))
        batch_op.drop_index(batch_op.f('ix_appointments_hospital_id'))
        batch_op.drop_index(batch_op.f('ix_appointments_ehr_appointment_id'))
        batch_op.drop_index(batch_op.f('ix_appointments_doctor_id'))
        batch_op.drop_index(batch_op.f('ix_appointments_appointment_number'))
        batch_op.drop_index('idx_appointments_hospital_status')
        batch_op.drop_index('idx_appointments_doctor_date')

    op.drop_table('appointments')
    op.drop_table('ai_contexts')
    with op.batch_alter_table('time_slots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_time_slots_status'))
        batch_op.drop_index(batch_op.f('ix_time_slots_start_time'))
        batch_op.drop_index(batch_op.f('ix_time_slots_doctor_id'))

    op.drop_table('time_slots')
    with op.batch_alter_table('calendars', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_calendars_hospital_id'))
        batch_op.drop_index(batch_op.f('ix_calendars_doctor_id'))

    op.drop_table('calendars')
    op.drop_table('availability_schedules')
    with op.batch_alter_table('ai_conversations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_conversations_status'))
        batch_op.drop_index(batch_op.f('ix_ai_conversations_session_id'))
        batch_op.drop_index(batch_op.f('ix_ai_conversations_patient_id'))
        batch_op.drop_index(batch_op.f('ix_ai_conversations_hospital_id'))

    op.drop_table('ai_conversations')
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_patients_primary_hospital_id'))
        batch_op.drop_index(batch_op.f('ix_patients_phone'))
        batch_op.drop_index(batch_op.f('ix_patients_patient_mrn'))
        batch_op.drop_index(batch_op.f('ix_patients_external_patient_id'))
        batch_op.drop_index(batch_op.f('ix_patients_email'))

    op.drop_table('patients')
    with op.batch_alter_table('hospital_admins', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hospital_admins_hospital_id'))
        batch_op.drop_index(batch_op.f('ix_hospital_admins_email'))

    op.drop_table('hospital_admins')
    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_doctors_specialty_id'))
        batch_op.drop_index(batch_op.f('ix_doctors_specialty'))
        batch_op.drop_index(batch_op.f('ix_doctors_is_active'))
        batch_op.drop_index(batch_op.f('ix_doctors_hospital_id'))
        batch_op.drop_index(batch_op.f('ix_doctors_external_provider_id'))
        batch_op.drop_index(batch_op.f('ix_doctors_department_id'))
        batch_op.drop_index('idx_doctors_hospital_specialty')

    op.drop_table('doctors')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_hospital_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('questionnaires', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_questionnaires_specialty_id'))
        batch_op.drop_index(batch_op.f('ix_questionnaires_hospital_id'))

    op.drop_table('questionnaires')
    with op.batch_alter_table('external_identifier_mappings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_external_identifier_mappings_internal_id'))
        batch_op.drop_index(batch_op.f('ix_external_identifier_mappings_hospital_id'))
        batch_op.drop_index(batch_op.f('ix_external_identifier_mappings_external_id'))
        batch_op.drop_index('idx_ext_mapping_lookup')

    op.drop_table('external_identifier_mappings')
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_departments_hospital_id'))

    op.drop_table('departments')
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_events_resource_type'))
        batch_op.drop_index(batch_op.f('ix_audit_events_hospital_id'))
        batch_op.drop_index(batch_op.f('ix_audit_events_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_events_correlation_id'))
        batch_op.drop_index(batch_op.f('ix_audit_events_action'))
        batch_op.drop_index('idx_audit_correlation_tenant')

    op.drop_table('audit_events')
    with op.batch_alter_table('specialties', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_specialties_name'))

    op.drop_table('specialties')
    with op.batch_alter_table('mock_ehr_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mock_ehr_records_idempotency_key'))

    op.drop_table('mock_ehr_records')
    with op.batch_alter_table('hospitals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hospitals_status'))
        batch_op.drop_index(batch_op.f('ix_hospitals_license_number'))

    op.drop_table('hospitals')
    op.drop_table('chaos_settings')
    # ### end Alembic commands ###
